"""add vehicle extra fields

Revision ID: 13cc9d3b4efe
Revises: 4bc0d8f3df66
Create Date: 2026-05-21 10:09:59.447294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cc9d3b4efe'
down_revision = '4bc0d8f3df66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condition', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('body_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('engine_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('color')
        batch_op.drop_column('engine_size')
        batch_op.drop_column('body_type')
        batch_op.drop_column('condition')

    # ### end Alembic commands ###
