"""fresh schema

Revision ID: 242ebb905c8c
Revises: 606b1a936ff9
Create Date: 2026-05-20 14:50:02.252120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242ebb905c8c'
down_revision = '606b1a936ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('previous_owners', sa.Integer(), nullable=True),
    sa.Column('service_history_available', sa.Boolean(), nullable=True),
    sa.Column('accident_history', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('price_assessment', sa.String(length=100), nullable=False),
    sa.Column('rule_score', sa.Float(), nullable=False),
    sa.Column('ai_penalty', sa.Float(), nullable=False),
    sa.Column('ai_results', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_analysis_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('vehicle_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_images_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_images_vehicle_id'))

    op.drop_table('vehicle_images')
    with op.batch_alter_table('vehicle_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_analysis_vehicle_id'))

    op.drop_table('vehicle_analysis')
    op.drop_table('vehicle')
    op.drop_table('users')
    # ### end Alembic commands ###
