"""empty message

Revision ID: 338890e2a721
Revises: 13cc9d3b4efe
Create Date: 2026-05-24 00:33:29.121595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338890e2a721'
down_revision = '13cc9d3b4efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('previous_owners')
        batch_op.drop_column('accident_history')
        batch_op.drop_column('service_history_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_history_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('accident_history', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previous_owners', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
