"""Add public_id to vehicle_images

Revision ID: 59fb18904f9a
Revises: 338890e2a721
Create Date: 2026-05-24 11:34:12.278438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fb18904f9a'
down_revision = '338890e2a721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_images', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
