"""Remove file_path from vehicle_images model

Revision ID: 85ae79303c48
Revises: 242ebb905c8c
Create Date: 2026-05-20 16:45:20.196776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ae79303c48'
down_revision = '242ebb905c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_analysis_vehicle_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_analysis_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###
