"""initial migration

Revision ID: c71108009ff6
Revises: 
Create Date: 2026-05-20 02:39:36.704292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c71108009ff6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('vehicles')
    with op.batch_alter_table('vehicle_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_images_vehicle_id'))

    op.drop_table('vehicle_images')
    op.drop_table('listings')
    op.drop_table('valuations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valuations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('condition_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price_low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price_mid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price_high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('positives', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('concerns', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('valuations_listing_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('valuations_pkey')),
    sa.UniqueConstraint('listing_id', name=op.f('valuations_listing_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('listings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('listings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('listings_pkey'))
    )
    op.create_table('vehicle_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('image_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('vehicle_images_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicle_images_pkey'))
    )
    with op.batch_alter_table('vehicle_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_images_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asking_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('fuel_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('transmission', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('previous_owners', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_history_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('accident_history', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('age_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('annual_mileage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('condition_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('price_assessment', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('vehicles_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
